# Generated by Django 2.1.5 on 2019-03-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subheading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subheading_title', models.CharField(max_length=200)),
                ('subheading_content', models.TextField()),
            ],
        ),
    ]
