# Generated by Django 2.1.5 on 2019-04-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190331_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['pk'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['pk'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['pk'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='examlog',
            options={'ordering': ['pk'], 'verbose_name': 'Examlog', 'verbose_name_plural': 'Examlogs'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='subheading',
            options={'ordering': ['pk'], 'verbose_name': 'Subheading', 'verbose_name_plural': 'Subheadings'},
        ),
        migrations.AddField(
            model_name='exam',
            name='goal',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
