# Generated by Django 2.1.5 on 2019-03-23 19:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190323_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subheading',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
