# Generated by Django 2.1.5 on 2019-04-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190426_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='examlog',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
